exp1 implementation
architag/evaluation_repo pull request #1
Opened 2021-03-11 06:27 UTC by architag

2021-03-11 10:14 UTC, gagan93jtg approved these changes

2021-03-11 10:14 UTC, gagan93jtg commented on exp1.html
> +<!DOCTYPE html>
pls replicate design properly, compare using pixel perfect plugin

2021-03-11 10:15 UTC, gagan93jtg requested changes

2021-03-11 10:15 UTC, gagan93jtg commented on exp1_style.css
> +}
1. Read about red symbol and how to remove.
2. What is the use of .DS_Store file?

2021-03-11 10:15 UTC, gagan93jtg commented on exp1_style.css
> +	border-color: rgb(237, 237, 237);
use 2 space indentation, not tab

2021-03-11 10:45 UTC, merged

2021-03-12 04:15 UTC, architag commented
> @architag: Why did we merge this PR??

Sir, I changed the indentation and newline at the end of file. Also I thought it said changes were approved.