adding submission for exercise 2
architag/evaluation_repo pull request #2
Opened 2021-03-12 05:03 UTC by architag

2021-03-12 06:00 UTC, neeraj33negi requested changes

2021-03-12 06:00 UTC, neeraj33negi commented on Exercise 2/exp2_style.css
> +#text1, #text2, #text3, #text4 {
same here

2021-03-15 03:17 UTC, neeraj33negi approved these changes

2021-03-15 05:49 UTC, gagan93jtg approved these changes

2021-03-15 05:52 UTC, merged